#ifndef WII_H
#define WII_H

#include <ogc/pad.h>

#define WII_JOY_A     PAD_BUTTON_A
#define WII_JOY_B     PAD_BUTTON_B
#define WII_JOY_X     PAD_BUTTON_X
#define WII_JOY_Y     PAD_BUTTON_Y
#define WII_JOY_LEFT  PAD_BUTTON_LEFT
#define WII_JOY_RIGHT PAD_BUTTON_RIGHT
#define WII_JOY_UP    PAD_BUTTON_UP
#define WII_JOY_DOWN  PAD_BUTTON_DOWN
#define WII_JOY_Z     PAD_TRIGGER_Z
#define WII_JOY_R     PAD_TRIGGER_R
#define WII_JOY_L     PAD_TRIGGER_L
#define WII_JOY_START PAD_BUTTON_START
#define WII_JOY_MENU  PAD_BUTTON_MENU

#endif
